# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5410381efa63bd0a45f33cf3e0f949082839093f70c59987a4d247ae2243f65466536e0774f39d02757ffdcaafc8a824cc3a58e902f21d018b27fb3c7f69eb1

test:
  secret_key_base: ebeb6408b7411cd55e845a9406975ca2adb96d414f6686b6b5355958dacf36aea34b8f5038ea537a9c19c1c4622ec8fe8d092fdf30b60763e002edc231ca52eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
